
const PrivacyPolicy = () => {
  return (
    <section className="content">
      <h1 className="text-center">Privacy Policy</h1>
      <br />
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        This privacy policy describes how the personal information we collect, use, and disclose is used by us. It also describes the choices available to you regarding our use of your personal information and how you can access and update this information.
      </p>
      <br />
      <h2 className="text-center">Interpretation and Definitions</h2>
      <br />
      <h3 className="text-center">Interpretation</h3>
      <br />
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>
      <br />
      <h3 className="text-center">Definitions</h3>
      <br />
      <p>
        For the purposes of this Privacy Policy:
      </p>
      <br />
      <ul>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Company Name.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website.
          </p>
        </li>
        <li>
          <p>
            <strong>Country</strong> refers to: India
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to Company Name, accessible from https://www.companyname.com
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>
      <br />
      <h2 className="text-center">Collecting and Using Your Personal Data</h2>
      <br />
      <h3 className="text-center">Types of Data Collected</h3>
      <br />
      <h4 className="text-center">Personal Data</h4>
      <br />
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <br />
      <ul>
        <li>
          <p>
            Email address
          </p>
        </li>
        <li>
          <p>
            First name and last name
          </p>
        </li>
        <li>
          <p>
            Phone number
          </p>
        </li>
        <li>
          <p>
            Address, State, Province, ZIP/Postal code, City
          </p>
        </li>
        <li>
          <p>
            Cookies and Usage Data
          </p>
        </li>
      </ul>
      <br />
      <h4 className="text-center">Usage Data</h4>
      <br />
      <p>
        Usage Data is collected automatically when using the Service.
      </p>
      <br />
      <p>
        Usage Data may include information such as Your Device&apos s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>
      <br />
      <p>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </p>
      <br />
      <p>
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
      </p>
      <br />
      <h4 className="text-center">Tracking Technologies and Cookies</h4>
      <br />
      <p>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
      </p>
      <br />
      <p>
        You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
      </p>
      <br />
      <p>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.
      </p>
      <br />
      <p>
        We use both Session and Persistent Cookies for the purposes set out below:
      </p>
      <br />
      <ul>
        <li>
          <p>
            <strong>Necessary / Essential Cookies</strong>
          </p>
          <br />
          <p>Type: Session Cookies</p>
          <br />
          <p>Administered by: Us</p>
          <br />
          <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
        </li>
        <li>
          <p>
            <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          </p>
          <br />
          <p>Type: Persistent Cookies</p>
          <br />
          <p>Administered by: Us</p>
          <br />
          <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
        </li>
        <li>
          <p>
            <strong>Functionality Cookies</strong>
          </p>
          <br />
          <p>Type: Persistent Cookies</p>
          <br />
          <p>Administered by: Us</p>
          <br />
          <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your language or login information.</p>
        </li>
      </ul>
      <br />
      <p>
        For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
      </p>
      <br />
      <h4 className="text-center">Service Providers</h4>
      <br />
      <p>
        We may employ third party companies and individuals to facilitate Our Service, to provide Our
        Service on behalf of
        You, or to perform Service-related services
        on behalf of You. These third parties have access to Your Personal Data only to perform these tasks on Our behalf and are obligated not to disclose or use it for any other purpose.
      </p>
      <br />
      <h4 className="text-center">Security</h4>
      <br />
      <p>
        We value your trust in providing us your Personal Data, thus we are striving
        to use commercially acceptable means of protecting it. But remember that no method
        of transmission over the internet, or method of electronic storage is 100% secure
        and reliable, and We cannot guarantee its absolute security.
      </p>
      <br />
      <h4 className="text-center">Links to Other Sites</h4>
      <br />
      <p>
        Our Service may contain links to other sites. If You click on a
        third party link, You will be directed to that third party&apos s site. Note
        that these external sites are not operated by Us. Therefore, We
        strongly advise You to review the Privacy Policy of these websites
        for more information on the privacy practices and policies applicable to them. If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.
      </p>
      <br />
      <h4 className="text-center">Children&apos s Privacy</h4>
      <br />
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone
        under the age of 13. If You are a parent or guardian and You are
        aware that Your child has provided Us with Personal Data, please
        contact Us. If We become aware that We have collected Personal
        Data from anyone under the age of 13 without verification of
        parental consent, We take steps to remove that information from
        Our servers.
      </p>
      <br />
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We
        may require Your parent&apos s consent before We collect and use
        that information.
      </p>
      <br />
      <h4 className="text-center">Changes to This Privacy Policy</h4>
      <br />
      <p>
        We may update Our Privacy Policy from time to time. We will
        notify You of any changes by posting the new Privacy Policy on
        this page.
      </p>
      <br />
      <p>
        We will let You know via email and/or a prominent notice on
        Our Service, prior to the change becoming effective and update
        the &quot;Last updated&quot; date at the top of this Privacy Policy.
      </p>
      <br />
      <p>
        You are advised to review this Privacy Policy periodically for
        any changes. Changes to this Privacy Policy are effective when
        they are posted on this page.
      </p>
      <br />
      <h4 className="text-center">Contact Us</h4>
      <br />
      <p>
        If you have any questions about this Privacy Policy, You can
        contact us:
      </p>
      <br />
      <ul>
        <li>
          <p>
            By email: 0E8iA@example.com
          </p>
        </li>
        <li>
          <p>
            By visiting this page on our website: https://www.ourwebsite.com/contact
          </p>
        </li>
      </ul>
    </section>
  )
}

export default PrivacyPolicy;